force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Movie category</description>
    <label>Genre</label>
    <referenceTo>Genre__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MovieServiceTest.cls
@isTest
private class MovieServiceTest {

    @isTest
    static void testCreateMovie(){

        Movie__c m = new Movie__c(
            Name = 'Interstellar',
            Genre__c = 'Sci-Fi'
        );

        insert m;

        List<Movie__c> movies = MovieService.getAllMovies();

        System.assert(
            movies.size() > 0,
            'Movie list should contain at least one movie after insertion'
        );
    }

}